name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Create API Gateway Integration
      run: |
        integration_id=$(aws apigatewayv2 create-integration --api-id nkg2365i5f --integration-type "AWS_PROXY" --integration-uri arn:aws:apigateway:ap-northeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-2:${{ secrets.AWS_ACCOUNT_ID }}:function:test2/invocations --payload-format-version "2.0" --query 'IntegrationId' --output text)
        echo "INTEGRATION_ID=$integration_id" >> $GITHUB_ENV

    - name: Create API Gateway Route
      run: |
        route_exists=$(aws apigatewayv2 get-routes --api-id nkg2365i5f --query "Items[?RouteKey=='ANY /{proxy+}'].RouteId" --output text)
        if [ -z "$route_exists" ]; then
          aws apigatewayv2 create-route --api-id nkg2365i5f --route-key "ANY /{proxy+}" --target integrations/${{ env.INTEGRATION_ID }}
        else
          echo "Route ANY /{proxy+} already exists, skipping creation."
        fi
